//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductStore.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selling
    {
        public int Id { get; set; }
        public int IdGood { get; set; }
        public int IdUser { get; set; }
        public double Cost { get; set; }
        public int Amount { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual User User { get; set; }
    }
}
